Repository laminas/laminas-i18n, pull requests merged in 2020-03, with the labels that each got.

#13 Update filtered number in docs
  docs/book/filters.md
Labels: Bug, Documentation

#14 Fixes #8 - Missing documentation for Laminas\I18n\Validator\PhoneNumber
  docs/book/validators/phone-number.md
  mkdocs.yml
Labels: Documentation

#15 Fixes #9 - Missing documentation for Laminas\I18n\Validator\DateTime
  docs/book/validators/date-time.md
  mkdocs.yml
Labels: Documentation

#16 Adds new documentation for PostCode validator
  docs/book/validators.md
  docs/book/validators/post-code.md
  mkdocs.yml
Labels: Documentation, Enhancement

#19 Adds new documentation for IsFloat validator
  docs/book/validators.md
  docs/book/validators/is-float.md
  mkdocs.yml
Labels: Documentation, Enhancement

#21 Adds new page for migration to documentation
  docs/book/migration/migration-to-v2.4.md
  mkdocs.yml
Labels: Documentation, Enhancement

#24 Adds stand-alone usage to documentation
  docs/book/application-integration/stand-alone.md
  mkdocs.yml
Labels: Documentation, Enhancement

#26 Adds new introduction page for validators
  docs/book/validators.md
  docs/book/validators/introduction.md
  mkdocs.yml
Labels: Documentation, Enhancement

#25 Adds documentation for caching, factory and formats
  docs/book/translation.md
  docs/book/translator/caching.md
  docs/book/translator/factory.md
  docs/book/translator/format-examples.md
  mkdocs.yml
Labels: Documentation, Enhancement

#28 Adds new documentation for view helpers
  docs/book/view-helpers.md
  docs/book/view-helpers/currency-format.md
  docs/book/view-helpers/date-format.md
  docs/book/view-helpers/introduction.md
  docs/book/view-helpers/number-format.md
  docs/book/view-helpers/plural.md
  docs/book/view-helpers/translate-plural.md
  docs/book/view-helpers/translate.md
  mkdocs.yml
Labels: Documentation, Enhancement

#30 Adds IntlCalendar as possible value for DateFormat view helper in documentation
  docs/book/view-helpers/date-format.md
Labels: Bug, Documentation

#32 Adds documentation for events of the translator
  docs/book/translator/events.md
  mkdocs.yml
Labels: Documentation, Enhancement

#34 Adds the explanation for IDE auto-completion in templates back again
  docs/book/view-helpers/introduction.md
Labels: Documentation, Enhancement
