Repository laminas/laminas-i18n, pull requests merged in 2021-04, with the labels that each got.

#46 Adds Laminas GHA CI Workflow
  .gitattributes
  .github/workflows/continuous-integration.yml
  .gitignore
  .travis.yml
  CHANGELOG.md
  README.md
  composer.lock
  phpunit.xml.dist
  test/View/Helper/CurrencyFormatTest.php
Labels: Enhancement

#44 Adds I18n resources as related component
  mkdocs.yml
Labels: Documentation, Enhancement

#47 Fix documentation linting errors
  docs/book/filters/alnum.md
  docs/book/filters/alpha.md
  docs/book/filters/introduction.md
  docs/book/filters/number-parse.md
  docs/book/migration/migration-to-v2.4.md
  docs/book/translator/caching.md
  docs/book/translator/events.md
  docs/book/translator/factory.md
  docs/book/translator/format-examples.md
  docs/book/validators/alnum.md
  docs/book/validators/alpha.md
  docs/book/validators/date-time.md
  docs/book/validators/introduction.md
  docs/book/validators/is-float.md
  docs/book/validators/is-int.md
  docs/book/validators/phone-number.md
  docs/book/validators/post-code.md
  docs/book/view-helpers/currency-format.md
  docs/book/view-helpers/date-format.md
  docs/book/view-helpers/introduction.md
  docs/book/view-helpers/number-format.md
  docs/book/view-helpers/plural.md
  docs/book/view-helpers/translate-plural.md
  docs/book/view-helpers/translate.md
Labels: Documentation
