Repository laminas/laminas-i18n, pull requests merged in 2021-11, with the labels that each got.

#62 Allow installation on PHP 8.1
  .laminas-ci.json
  composer.json
  composer.lock
  test/View/Helper/DateFormatTest.php
Labels: Enhancement, hacktoberfest-accepted

#64 Rewrites blockquotes to admonitions / call-outs
  docs/book/filters/introduction.md
  docs/book/filters/number-parse.md
  docs/book/translation.md
  docs/book/translator/caching.md
  docs/book/translator/events.md
  docs/book/validators/introduction.md
  docs/book/validators/phone-number.md
  docs/book/view-helpers/introduction.md
  docs/book/view-helpers/plural.md
Labels: Documentation, Enhancement

#65 Marks PostCode::setService() and PostCode::getService() as deprecated
  src/Validator/PostCode.php
Labels: Feature Removal
