Repository laminas/laminas-i18n, pull requests merged in 2024-07, with the labels that each got.

#128 `Laminas\Translator`
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Translator/TranslatorInterface.php
Labels: Enhancement

#123 Update caching documentation for laminas-cache
  docs/book/translator/caching.md
Labels: Bug, Documentation

#130 Add service manager alias for `Laminas\Translator\TranslatorInterface`
  src/ConfigProvider.php
  src/Module.php
Labels: Bug

#131 2.27.1 into 2.28.x merge up
  src/ConfigProvider.php
  src/Module.php
Labels: Bug
